<?php

/**
 * @file
 * Contains mollo_artist.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\mollo_utils\Utility\ViewFilter;

/**
 * Implements hook_help().
 */
function mollo_artist_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mollo_artist module.
    case 'help.page.mollo_artist':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Artist Module for Mollo Events') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mollo_artist_theme() {
  return [
    'mollo_artist' => [
      'render element' => 'children',
    ],
  ];
}

function mollo_artist_form_alter(&$form, &$form_state, $form_id) {

  if ($form['#id'] === 'views-exposed-form-mollo-artist-roles-admin-list'

  ) {

    $form = ViewFilter::filter_mollo_event($form);

  }

}
